version: '3.9'

services:
  app:
    container_name: app
    image: exc02/php8.3-fpm-symfony:latest
    build:
      context: ./_docker/local/php-fpm
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./dev/:/var/www
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
    ports:
      - "8881:8000"
    networks:
      - app_network
    depends_on:
      - database

  database:
    container_name: app_db
    image: 'postgres:15-alpine'
    ports:
      - '5555:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-db}'
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'app_db:/var/lib/postgresql/data:rw'
    networks:
      - app_network

volumes:
  app_db:
    driver: local

networks:
  app_network:
    driver: bridge
